### ISSUE TITLE
Encoding fix

### ISSUE THREAD

**Issue by Dzejro** [LBeaudoux/iso639#1] opened 2020-07-23 06:10 UTC
Last version https://pypi.org/project/iso639-lang/ can't read .tab file, I got exception. 
Please fix it. 

Thank you

```python
def _load_iso639_table():
    """Load the iso639 table from its tab file.
    """
    with open(TABLE_PATH, encoding='utf-8') as f:
        reader = csv.reader(f, delimiter="\t")
        next(reader)

        return [row for row in reader]
```

**Comment by LBeaudoux** [comment] 2020-08-25 15:04
I can't reproduce your bug on my machine.
Please help me finding a solution to your problem by letting me know:
- he stack trace and the exception you get 
- the version of the liso639-lang ibrary you are using
- the version of Python you are using
- the name and version of your OS

**Comment by LBeaudoux** [comment] 2020-09-29 21:11
Thanks for reporting this bug on Windows. It's been fixed in the latest update of the package.

**Closed** 2020-09-29 21:11 UTC
